### ISSUE TITLE
SetRank w/ DLA learning error

### ISSUE THREAD

**Issue by utopn** [ULTR-Community/ULTRA_pytorch#8]
i'm trying to reproduce the algorithm on my local machine, w/ different IDE,
i has these settings:

```
exp_settings = {
    "train_input_feed":"ultra.input_layer.ClickSimulationFeed",
    "train_input_hparams":"",
    "valid_input_feed":"ultra.input_layer.DirectLabelFeed",
    "valid_input_hparams":"",
    "test_input_feed":"ultra.input_layer.DirectLabelFeed",
    "test_input_hparams":"",
    "ranking_model":"ultra.ranking_model.SetRank",
    "ranking_model_hparams":" ",
    "learning_algorithm": "ultra.learning_algorithm.dla.DLA",
    "learning_algorithm_hparams":"",
    "metrics": [
        "mrr", "ndcg"
    ],
    "metrics_topn" : [3,5,10],
    "objective_metric": "ndcg_10",
    "max_candidate_num": 10 #added after error in DLA default setting setrank*
}
```

the error i got, when i execute 
```model = create_model(exp_settings, train_set)```
 
```
Reading finish: 0 lines
Remove 7 invalid queries.
Data reading finish!
Finished reading 20 queries with lists.
Read data from /ULTRA/example/toy/data//valid in libsvm format.
Reading finish: 0 lines
Remove 3 invalid queries.
Data reading finish!
Finished reading 6 queries with lists.
Train Rank list size 9
Valid Rank list size 9
Users can only see the top 9 documents for each query in training.
Creating model...
Build DLA
Traceback (most recent call last):

  File "/tmp/ipykernel_1350348/2504700013.py", line 151, in <module>
    model = create_model_main(exp_settings, train_set)

  File "/tmp/ipykernel_1350348/2504700013.py", line 99, in create_model_main
    model = ultra.utils.find_class(exp_settings['learning_algorithm'])(data_set, exp_settings)

  File "/ULTRA/ultra/learning_algorithm/dla.py", line 102, in __init__
    self.rank_model = self.create_model(self.feature_size)

  File "/ULTRA/ultra/learning_algorithm/base_algorithm.py", line 164, in create_model
    model = utils.find_class(

TypeError: 'module' object is not callable
```

There something wrong w/ function or nesting parameters here: 
```
def create_model(self, feature_size):
      if not hasattr(self, "model"):
              model = utils.find_class(
                  self.exp_settings['ranking_model'])(
                  self.exp_settings['ranking_model_hparams'], feature_size)
      return model
```
debugging lead to setrank() model inside of DLA learning algorithm which is stuck w/ this line of code: 
```
self.exp_settings['ranking_model_hparams'], feature_size)"
```

**Comment by utopn** [comment]
actually i found :
in ultra/ranking_model/__init__.py
uncommented 
```
from .SetRank import *
```
